# -*- coding: utf-8 -*-
"""Klasifikasi Stroke

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_JboFtm2MBU9chsy6df8Lmt1vA_wehk
"""

import pandas as pd
stroke = pd.read_csv("/content/brain_stroke.csv")

stroke.info()

stroke.head()

"""Pengecekan nilai NaN"""

stroke.isnull().sum()

"""Melakukan konversi data kategori menjadi numerik"""

stroke['gender'] = stroke['gender'].map({'Male': 1, 'Female': 0})
stroke['ever_married'] = stroke['ever_married'].map({'Yes': 1, 'No': 0})
stroke['work_type'] = stroke['work_type'].map({'Private': 0, 'Self-employed': 1, 'Govt_job': 2, 'children': 3})
stroke['Residence_type'] = stroke['Residence_type'].map({'Urban': 0, 'Rural': 1})
stroke['smoking_status'] = stroke['smoking_status'].map({'never smoked': 0, 'formerly smoked': 1, 'smokes': 2, 'Unknown': 3})

stroke.head()

stroke.drop('gender',axis=1,inplace=True)
stroke.head()

"""Memisahkan atribut dengan label dimana X itu atribut dan Y itu label"""

X = stroke[['age','hypertension','heart_disease','ever_married','work_type','Residence_type','avg_glucose_level','bmi','smoking_status']]
Y = stroke['stroke']

"""Membagi dataset menjadi data latih dan data uji"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(X,Y, test_size=0.1, random_state=10)

from sklearn.tree import DecisionTreeClassifier

# Membuat model decision tree
tree_model = DecisionTreeClassifier()

# Melatih model menggunakan data latih dengan fungsi fit
tree_model = tree_model.fit(x_train,y_train)

"""Evaluasi model untuk menguji seberapa baik model yang digunakan dan akurasi"""

from sklearn.metrics import accuracy_score

mapping = {0: 'Tidak Stroke', 1: 'Stroke'}

print(mapping, '\n')

y_pred = tree_model.predict(x_test)

accuracy_score = round(accuracy_score(y_pred, y_test), 3)

print('Akurasi : ', accuracy_score)

"""Prediksi model"""

print(tree_model.predict([[67,0,1,1,0,0,228.69,36.6,1]]))

print(tree_model.predict([[58,1,0,1,0,0,87.96,39.2,0]]))

"""Visualisasi Data"""

from sklearn.tree import export_graphviz
import graphviz

export_graphviz(tree_model,
                out_file='brain_stroke_tree.dot',
                feature_names=['age','hypertension','heart_disease','ever_married','work_type','Residence_type','avg_glucose_level','bmi','smoking_status'],
                class_names=['0','1'],
                rounded=True,
                filled=True)

with open('brain_stroke_tree.dot') as t:
  dot_graph = t.read()

graphviz.Source(dot_graph)